#pragma once


#define NUM_COLS 10
#define NUM_ROWS 22
#define GRID_SIZE 25
#define FIELD_ORIGIN_X 300
#define FIELD_ORIGIN_Y 100
#define DROP_SPEED 0.5f
#define MAX_DROP_SPEED 16.0f
#define NUM_PREVIEW_PIECES 3
#define INPUT_REPEAT_START_DELAY 0.5f
#define INPUT_REPEAT_INTERVAL 0.1f
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define OUTLINE_THICKNESS (2.0f)
